name: Deployment (Container)

on:
  push:
    branches:
      - master
      - dev

env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    name: Run Tests in Container
    runs-on: ubuntu-latest  # ✅ REQUIRED FIELD
    container:
      image: node:18
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSTER_ADDRESS: mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: 8080
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
        options: --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Start server and wait for it
        run: npm start & npx wait-on http://127.0.0.1:$PORT

      - name: Run tests
        run: npm test

      - name: Output information
        run: echo "MONGODB_USERNAME: $MONGODB_USERNAME"

  deploy:
    name: Deployment Step
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Output Deployment Info
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "PORT: 3000"
